"""Add relationship between Patient and DailyTrack

Revision ID: ad0067e7ff19
Revises: 5845e8573737
Create Date: 2023-12-17 00:57:53.595060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0067e7ff19'
down_revision: Union[str, None] = '5845e8573737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailytrack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patNumber', sa.Integer(), nullable=False),
    sa.Column('bodyTemperature', sa.Text(), nullable=False),
    sa.Column('bloodPressure', sa.Text(), nullable=False),
    sa.Column('diet', sa.Text(), nullable=False),
    sa.Column('waterIntake', sa.Text(), nullable=False),
    sa.Column('medicationEffectiveness', sa.Text(), nullable=False),
    sa.Column('sleepDuration', sa.Text(), nullable=False),
    sa.Column('nausea', sa.Boolean(), nullable=False),
    sa.Column('tiredness', sa.Boolean(), nullable=False),
    sa.Column('otherSymptoms', sa.Text(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dailytrack')
    # ### end Alembic commands ###
