"""correcting tables

Revision ID: b7fd380deb1a
Revises: ad0067e7ff19
Create Date: 2023-12-20 10:34:22.820169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7fd380deb1a'
down_revision: Union[str, None] = 'ad0067e7ff19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patNumber', sa.Integer(), nullable=False),
    sa.Column('bodyTemperature', sa.Text(), nullable=False),
    sa.Column('bloodPressure', sa.Text(), nullable=False),
    sa.Column('diet', sa.Text(), nullable=False),
    sa.Column('waterIntake', sa.Text(), nullable=False),
    sa.Column('medicationEffectiveness', sa.Text(), nullable=False),
    sa.Column('sleepDuration', sa.Text(), nullable=False),
    sa.Column('nausea', sa.Boolean(), nullable=False),
    sa.Column('tiredness', sa.Boolean(), nullable=False),
    sa.Column('otherSymptoms', sa.Text(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dailytrack')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailytrack',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patNumber', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bodyTemperature', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bloodPressure', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('diet', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('waterIntake', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('medicationEffectiveness', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sleepDuration', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nausea', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('tiredness', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('otherSymptoms', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='dailytrack_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dailytrack_pkey')
    )
    op.drop_table('daily_tracks')
    # ### end Alembic commands ###
